### ISSUE TITLE
Error message while running trash

### ISSUE THREAD

**Issue by smousa** [rancher/trash#12]
Can you tell me what I am doing wrong here: 

FATA[0000] `git checkout -f --detach remote-develop` failed:
fatal: '--detach' cannot be used with '-b/-B/--orphan'

**Comment by smousa** [comment]
Workaround: I used the commit hash rather than the branch name and it worked.

**Comment by imikushin** [comment]
@smousa What package and branch did you try to use? I can try to reproduce the problem you were having.

**Comment by smousa** [comment]
Repo: https://github.com/control-center/go-zookeeper
Branch: remote-develop

**Comment by imikushin** [comment]
Thanks @smousa! I'm putting in the fix now

**Comment by imikushin** [comment]
This should be fixed in master now.
