### ISSUE TITLE
Feature Request : locating root GOPATH src directory for cleanup

### ISSUE THREAD

**Issue by karlmutch** [rancher/trash#27]
Looking at the start of the cleanup function in trash.go a relative hard coded path is used to navigate from the assumed location of the trash project to the src directory of the 3rd parties software system reusing trash.

The intent is that this location is then used to discover where the vendor directory of the users project is and traverse the vendor directory looking for unused projects and purging them.

_The proposal is that an alternative to the hard coded path is needed for supporting diverse package structuring situations._

**Comment from Ivan 👍** 

**@karlmutch** Go projects are supposed to have a certain directory structure. I admit we need to be more intelligent than just cd ../../../../src to get to source root. That will be addressed in a later release. Feel free to suggest a fix.

What I'm trying to do is to guess the root package of the project trash is being run against.

For example, rancher/os should reside in /go/src/github.com/rancher/os (if all your Go projects are using /go as GOPATH) or /home/ivan/src/rancher/os/src/github.com/rancher/os (I'm using a dedicated path as GOPATH for just RancherOS). In both cases I can tell the "root" package of the project is "github.com/rancher/os" from the directory structure of the checked out project.

For projects that do not observe the Go Way dir structure, we probably want to use the top level package key (like in trash's own trash.yml) to get the root package.

**Comment by karlmutch** [comment]
I begin looking at implementing code to walk up rather than down the directory tree looking for the first src directory that also has a vendor peer directory and then use that for the cleanup root directory.

**Comment by imikushin** [comment]
@karlmutch #28 should have resolved this. Feel free to close ;)
