### ISSUE TITLE
FATA[0041] It didn't work: '/home/me/code/go/src/src' does not exist or something: stat /home/me/code/go/src/src: no such file or directory

### ISSUE THREAD

**Issue by andradei** [rancher/trash#37]
I got this error message when running `trash`:

```
FATA[0041] It didn't work: '/home/me/code/go/src/src' does not exist or something: stat /home/me/code/go/src/src: no such file or directory
```

[This line](https://github.com/rancher/trash/blob/master/trash.go#L633) was the reason.

My project is in a path one level too deep for that line of code to work. Shouldn't getting the GOPATH be enough on that case?

Thanks for this simple, great tool.

**Comment by imikushin** [comment]
In general (and for your case in particular) it's a good practice to specify the root package for your project. In `trash.conf` that's the first non-commented line without the version. Like this:

```
# package
github.com/andradei/awesome-stuff

github.com/Sirupsen/logrus                      v0.10.0
github.com/urfave/cli                           v1.18.0

# ...
```

You may be right about getting the GOPATH. Of course, sometimes GOPATH specifies more than one path, but when it's just one dir and the project dir is it's subdirectory, that can help the guesswork.

**Comment by imikushin** [comment]
Now that trash uses GOPATH to guess the root package (if it's not set), I'm going to close this.

Feel free to reopen (or open a new one) if you feel `trash` can handle this better.
